services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_PASSWORD: "change-me"
    volumes:
      - pgdata:/var/lib/postgresql/18/main
    restart: unless-stopped
  comment-exporter:
    image: hj212223/bilibili:f6bfc94ae08203158e0cbd239b50c2556e59c69c
    environment:
      - APP_PG_DSN=postgresql://postgres:change-me@postgres:5432/postgres?sslmode=disable
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped
    command: >
      uv run main.py --serve
volumes:
  pgdata:
    driver: local
