services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_PASSWORD: "change-me"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/main
    restart: unless-stopped

volumes:
  pgdata:
    driver: local